name: RunWorkflowOnANotherRepository

on:
  workflow_call: 
    inputs:
     workflow-name:
        type: string
        required: true
    secrets:
     PAT:        
        required: true

jobs:
  triggerUITests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/KStobi90/TestSelenium/actions/workflows/${{ inputs.workflow-name }}.yml/dispatches \
          -d '{"ref":"main","inputs":{"coverage":"SMOKE"}}'
